//GET USERS
GET http://localhost:5000/users

// CREATE USER
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name" : "John Doe",
    "email" : "johndoe@gmail.com",
    "password" : "12345678",
    "confirmPassword" : "12345678",
    "role" : "user"
}

//GET USER By ID
###
GET http://localhost:5000/users/642aaa71fcfae68facd7d379


//GET USERS
###
GET http://localhost:5000/usaha


// CREATE USAHA
###
POST http://localhost:5000/usaha/642b026972a83f7d2c010aa5
Content-Type: application/json

{
    "name" : "Aci Bangor",
    "logo" : "logo.jpg"
}

// CREATE MENU
###
POST http://localhost:5000/menu/642b028572a83f7d2c010aa8
Content-Type: application/json

{
    "name" : "Chicken n Fries LG",
    "harga" : 20000,
    "diskon" : false,
    "potongan" : 0
}


###
// CHECK
GET http://localhost:5000/me

###
//LOGIN Admin
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email" : "johndoe@gmail.com",
    "password" : "12345678"
}

###
//LOGOUT
DELETE http://localhost:5000/logout